/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/astronaut_v07.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.hip} />
        <skinnedMesh
          geometry={nodes.BACKPACK.geometry}
          material={materials.BACKPACK_mtl}
          skeleton={nodes.BACKPACK.skeleton}
        />
        <skinnedMesh
          geometry={nodes.BACKPACK_CUBE_BLACK.geometry}
          material={materials.lambert1}
          skeleton={nodes.BACKPACK_CUBE_BLACK.skeleton}
        />
        <skinnedMesh geometry={nodes.belt.geometry} material={nodes.belt.material} skeleton={nodes.belt.skeleton} />
        <skinnedMesh
          geometry={nodes.BUST_RADIO.geometry}
          material={materials.RADIO_mtl1}
          skeleton={nodes.BUST_RADIO.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GLOVE_L.geometry}
          material={nodes.GLOVE_L.material}
          skeleton={nodes.GLOVE_L.skeleton}
        />
        <skinnedMesh
          geometry={nodes.GLOVE_R.geometry}
          material={nodes.GLOVE_R.material}
          skeleton={nodes.GLOVE_R.skeleton}
        />
        <skinnedMesh
          geometry={nodes.HELMET.geometry}
          material={nodes.HELMET.material}
          skeleton={nodes.HELMET.skeleton}
        />
        <skinnedMesh
          geometry={nodes.HELMET_cloth.geometry}
          material={nodes.HELMET_cloth.material}
          skeleton={nodes.HELMET_cloth.skeleton}
        />
        <skinnedMesh geometry={nodes.PANTS.geometry} material={materials.PANTS_mtl} skeleton={nodes.PANTS.skeleton} />
        <skinnedMesh geometry={nodes.SAFER.geometry} material={materials.SAFER_mtl} skeleton={nodes.SAFER.skeleton} />
        <skinnedMesh geometry={nodes.TORSO.geometry} material={materials.TORSO_mtl} skeleton={nodes.TORSO.skeleton} />
        <skinnedMesh geometry={nodes.VISOR.geometry} material={materials.VISORSG1} skeleton={nodes.VISOR.skeleton} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[0, 12.56, -41.86]} rotation={[1.6, 0, 0]}>
          <group position={[1.77, 1.77, -1.77]}>
            <group position={[-1.77, -1.77, 1.77]}>
              <group position={[-41.79, -8.82, -74.93]} rotation={[0.16, -1.11, 1.49]}>
                <group position={[-3.86, -10.93, -10.63]} rotation={[0.03, -0.2, 0.19]}>
                  <group position={[0, 0, 0]}>
                    <group position={[-9.67, 7.47, -6.34]} rotation={[-0.03, -0.13, -0.12]}>
                      <group position={[0, 0, 0]}>
                        <group position={[-19.3, -1.52, -12.42]} rotation={[0.01, -0.26, 0.02]}>
                          <group position={[0, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-17.09, -5.52, -20.21]} rotation={[0.01, -0.34, 0.03]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]}>
                      <group position={[-11.77, 4.36, -8.06]} rotation={[-0.03, -0.17, -0.06]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]}>
                            <group position={[-15.15, -7.7, -12.22]} rotation={[0.06, -0.22, 0.08]}>
                              <group position={[0, 0, 0]}>
                                <group position={[0, 0, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-14.87, -1.47, -17.09]} rotation={[-0.02, -0.29, -0.09]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]}>
                      <group position={[-10.8, 0.22, -7.32]} rotation={[0, -0.16, 0]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]}>
                            <group position={[-17.09, 0.39, -11.02]} rotation={[0, -0.23, 0]}>
                              <group position={[0, 0, 0]}>
                                <group position={[0, 0, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-17.58, 5.09, -18.28]} rotation={[-0.06, -0.31, -0.24]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]}>
                      <group position={[-5.33, -0.25, -3.87]} rotation={[0, -0.09, 0]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]}>
                            <group position={[-15.91, -9.13, -12.29]} rotation={[0.06, -0.23, 0.1]}>
                              <group position={[0, 0, 0]}>
                                <group position={[0, 0, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[32.21, -86.41, -69.55]} rotation={[0.98, 0.11, 0.73]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0.44, -9, -2.25]} rotation={[0.07, -0.04, 0.07]}>
                      <group position={[0, 0, 0]}>
                        <group position={[32.03, 3.22, 7.37]} rotation={[-0.02, 0.3, -0.03]}>
                          <group position={[0, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[40.44, 39.21, -112.98]} rotation={[0.16, -1.11, 1.49]}>
                <group position={[5.5, 0, -10]} rotation={[0, 0, -Math.PI / 2]} scale={[1.5, 1.5, 1.5]}>
                  <group position={[0, 0, -1]} />
                  <group position={[8.33, 0, -9.33]} scale={[0.55, 0.55, 0.55]} />
                </group>
              </group>
              <group position={[0, 0, 0]} rotation={[-0.01, -1.2, 0]}>
                <group position={[0, 0, 0]} rotation={[0.65, 0.15, 0.24]}>
                  <group position={[0, 0, 0]} rotation={[-0.78, -0.27, 0.05]} />
                </group>
              </group>
              <group position={[30.3, -1.66, -121.57]}>
                <group position={[18.75, -22.21, 0]} scale={[2.21, 2.21, 2.21]} />
              </group>
              <group position={[-55.16, -12.36, -123.18]} rotation={[-0.36, -1.5, 0]}>
                <group position={[68.88, -15.07, -30.65]} rotation={[0.4, 0.63, 0.94]} />
              </group>
            </group>
          </group>
          <group position={[1.77, 1.77, -1.77]}>
            <group position={[-1.77, -1.77, 1.77]}>
              <group position={[-40.42, 40.41, -113.43]} rotation={[-2.98, -1.11, 1.49]}>
                <group position={[-5.5, 0, 10]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.5, 1.5, 1.5]}>
                  <group position={[0, 0, -1]} />
                  <group position={[8.33, 0, -9.33]} scale={[0.55, 0.55, 0.55]} />
                </group>
              </group>
              <group position={[-103.98, 2.97, -185.75]} rotation={[-3.14, -0.87, 1.45]}>
                <group position={[0, 0, 0]} rotation={[0.03, -0.2, 0.19]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]} rotation={[-0.03, -0.13, -0.12]}>
                      <group position={[0, 0, 0]}>
                        <group position={[0, 0, 0]} rotation={[0.01, -0.26, 0.02]}>
                          <group position={[0, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0, 0]} rotation={[0.01, -0.43, 0.03]}>
                  <group position={[0, 0, 0]}>
                    <group position={[5.26, 0, -7.6]}>
                      <group position={[-5.26, 0, 7.6]} rotation={[-0.03, -0.17, -0.06]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]} rotation={[0.06, -0.22, 0.08]}>
                            <group position={[0, 0, 0]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0, 0]} rotation={[-0.02, -0.29, -0.09]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]}>
                      <group position={[0, 0, 0]} rotation={[0, -0.16, 0]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]} rotation={[0, -0.23, 0]}>
                            <group position={[0, 0, 0]}>
                              <group position={[0, 0, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0, 0]} rotation={[-0.06, -0.31, -0.24]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]}>
                      <group position={[0, 0, 0]} rotation={[0, -0.09, 0]}>
                        <group position={[0, 0, 0]}>
                          <group position={[0, 0, 0]} rotation={[0.06, -0.23, 0.1]}>
                            <group position={[0, 0, 0]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0, 0]} rotation={[0.98, 0.11, 0.73]}>
                  <group position={[0, 0, 0]}>
                    <group position={[0, 0, 0]} rotation={[0.07, -0.04, 0.07]}>
                      <group position={[0, 0, 0]}>
                        <group position={[0, 0, 0]} rotation={[-0.02, 0.3, -0.03]}>
                          <group position={[0, 0, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[0.69, 3.4, -0.15]} rotation={[3.13, -1.2, 0]}>
                <group position={[149.49, -59.17, 171.32]} rotation={[0.65, 0.15, 0.24]}>
                  <group position={[-130.59, -22.44, -194.85]} rotation={[-0.78, -0.27, 0.05]} />
                </group>
              </group>
              <group position={[15.74, -13.76, 121.73]} scale={[2, 2, 2]} />
              <group position={[0, 0, 0]} rotation={[0, 0, Math.PI]} />
              <group position={[0, 0, 0]} rotation={[2.78, -1.5, 0]}>
                <group position={[2.71, -127.44, 38.43]} rotation={[0.4, 0.63, 0.94]} />
              </group>
            </group>
          </group>
          <group position={[-1.1, -98.04, -98.86]} rotation={[1.57, 0, -Math.PI / 2]}>
            <group position={[4.17, 0.05, 16.76]} rotation={[0, -0.11, 0]}>
              <group position={[38.77, 2.01, 15.3]} rotation={[0, 0.16, 0]}>
                <group position={[51.95, -0.76, 12.76]} rotation={[0, 0.23, 0]}>
                  <group position={[0, 0, 0]} rotation={[3.11, -1.28, -1.6]} />
                  <group position={[0, 0, 0]} rotation={[3.11, -1.28, -1.6]} />
                  <group position={[0, 0, 0]} rotation={[0, -0.27, 0]}>
                    <group position={[0, 0, 0]} rotation={[0, -1.38, -Math.PI]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[18.37, -6.61, -12.91]} rotation={[0, 0, 1.17]}>
            <group position={[20.29, 8.7, -1.82]} rotation={[0.24, 0, 0.27]}>
              <group position={[-7.95, -0.07, 9.16]} rotation={[-Math.PI / 2, -0.04, -0.09]}>
                <group position={[34.08, 2.64, 0]} rotation={[0, 0, 0]}>
                  <group position={[-11, 0, 0]} rotation={[0, 0, 0]}>
                    <group position={[-16.03, 7.23, -0.24]} rotation={[0, -0.02, -0.45]} />
                  </group>
                  <group position={[0.01, -0.03, 0.09]} rotation={[1.61, 0, 0]} />
                </group>
              </group>
              <group position={[20.33, -22.78, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[-0.17, -22.78, 13.88]} rotation={[-Math.PI / 2, 0, 0]} scale={[3, 3, 3]} />
              <group position={[-19.26, 1.28, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[36.27, 1.28, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[44.46, 1.28, 5.97]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3, 3, 3]} />
            </group>
          </group>
          <group position={[1.77, 1.77, -1.77]}>
            <group position={[-1.77, -1.77, 1.77]}>
              <group position={[0, 0, 0]} rotation={[1.61, 0, 1.45]}>
                <group rotation={[0.01, -0.16, 0.04]}>
                  <group rotation={[-0.66, 1.16, 0.36]}>
                    <group rotation={[0, 0.45, -0.02]} />
                  </group>
                </group>
              </group>
              <group position={[17.12, 15.28, -55.28]}>
                <group position={[21.45, -24.58, 0]} scale={[2.21, 2.21, 2.21]} />
              </group>
              <group position={[18.37, -6.61, -12.91]} rotation={[0, 0, 1.17]} />
            </group>
          </group>
          <group position={[-18.37, -6.61, -12.91]} rotation={[0, 0, 1.98]}>
            <group position={[20.29, -8.7, -1.82]} rotation={[-0.24, 0, -0.27]}>
              <group position={[-7.95, 0.07, 9.16]} rotation={[-Math.PI / 2, -0.04, -0.09]}>
                <group position={[33.98, 2.63, -2.69]} rotation={[0, 0, 0]}>
                  <group position={[-10.97, 0, 0.86]} rotation={[0, 0, 0]}>
                    <group position={[-15.97, 7.23, 1.45]} rotation={[0, -0.02, -0.45]} />
                  </group>
                  <group position={[0.01, -0.05, 0.09]} rotation={[1.61, 0, 0]} />
                </group>
              </group>
              <group position={[20.33, -113.9, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[-0.17, -113.9, 13.88]} rotation={[-Math.PI / 2, 0, 0]} scale={[3, 3, 3]} />
              <group position={[-19.26, 6.38, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[36.27, 6.38, 13.88]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[3, 3, 3]} />
              <group position={[44.46, 6.38, 5.97]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[3, 3, 3]} />
            </group>
          </group>
          <group position={[21.11, 4.99, -171.02]} rotation={[-1.53, 0, 1.45]}>
            <group rotation={[0.01, -0.16, 0.04]}>
              <group position={[0, 0, 0]} rotation={[-0.66, 1.16, 0.36]}>
                <group rotation={[0, 0.45, -0.02]} />
              </group>
            </group>
          </group>
          <group position={[0.6, 14.72, -2.52]}>
            <group position={[-4.99, -21.18, 52.58]} scale={[2, 2, 2]} />
          </group>
          <group position={[-18.37, -6.61, -12.91]} rotation={[0, 0, 1.98]} />
        </group>
        <group position={[40.91, 7.61, -93.73]} rotation={[-0.36, -1.5, 0]} />
        <group position={[-40.89, 7.59, -93.72]} rotation={[2.74, -1.5, -0.04]} />
        <group position={[18.37, -6.61, -12.91]} rotation={[0, 0, 1.17]} />
        <group position={[-18.37, -6.61, -12.91]} rotation={[0, 0, 1.98]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-1.46, 1.15, 1.93]} rotation={[0, -0.01, 0]}>
          <group position={[19.57, -0.83, -149.9]} rotation={[-1.57, 0, -1.19]}>
            <group position={[30.13, 0.14, -0.62]} rotation={[0.69, -0.24, 0.16]} scale={[1, 1, 1]} />
          </group>
          <group position={[19.57, -0.83, -149.9]} rotation={[-1.57, 0.1, -1.19]} scale={[1, 1, 1]}>
            <group position={[30.13, 0, 0]} rotation={[0.71, -0.31, 0.21]} />
          </group>
        </group>
        <group position={[0, 25.8, -37.37]} rotation={[1.15, 0, 0]}>
          <group position={[-19.56, -0.81, -149.71]} rotation={[1.58, -0.01, -1.2]}>
            <group position={[-30.13, -0.14, 0.62]} rotation={[0.69, -0.24, 0.16]} />
          </group>
          <group position={[-19.56, -0.81, -149.71]} rotation={[1.11, 0, -1.16]} scale={[1, 1, 1]}>
            <group position={[-30.13, -0.14, 0.62]} rotation={[0.75, -0.55, 0.38]} />
          </group>
        </group>
        <group position={[0, 12.5, -42.93]} rotation={[1.65, 0, 0]}>
          <group position={[10.62, 2.5, -88.12]} rotation={[0, -1.45, -0.04]}>
            <group position={[35.83, 0, 0]} rotation={[0, -0.04, -0.16]}>
              <group position={[40.57, 0, 0]} rotation={[-0.33, -0.14, 1.18]}>
                <group position={[17.58, 0.47, -0.02]} rotation={[-0.01, 0.01, 0.45]} scale={[1, 1, 1]} />
              </group>
            </group>
          </group>
          <group position={[10.62, 2.5, -88.12]} rotation={[-1, -1.35, -0.62]} scale={[1, 1, 1]}>
            <group position={[35.83, 0, 0]} rotation={[-0.02, -0.09, -0.38]}>
              <group position={[40.57, 0, 0]} rotation={[0.1, 0.19, 0.94]} scale={[1, 1, 1]}>
                <group position={[17.58, 0.47, -0.02]} rotation={[-0.01, 0.01, 0.45]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 12.5, -42.93]} rotation={[1.65, 0, 0]}>
          <group position={[-10.62, 2.5, -88.12]} rotation={[3.14, -1.45, -0.04]} scale={[1, 1, 1]}>
            <group position={[-35.83, 0, 0]} rotation={[0, -0.04, -0.16]}>
              <group position={[-40.57, 0, 0]} rotation={[-0.33, -0.14, 1.18]}>
                <group position={[-17.58, -0.47, 0.02]} rotation={[-0.01, 0.01, 0.45]} scale={[1, 1, 1]} />
              </group>
            </group>
          </group>
          <group position={[-10.62, 2.5, -88.12]} rotation={[-2.37, -1.31, 1.15]}>
            <group position={[-35.83, 0, 0]} rotation={[-0.02, -0.09, -0.38]}>
              <group position={[-40.57, 0, 0]} rotation={[-0.27, 0.13, 0.95]} scale={[1, 1, 1]}>
                <group position={[-17.58, -0.47, 0.02]} rotation={[-0.01, 0.01, 0.45]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/astronaut_v07.gltf')
